### ISSUE TITLE
Is TSN supported ?

### ISSUE THREAD

**Issue by wwdok** [Media-Smart/volksdep#10]
TSN means Time-Sensitive Networking that is used in action recognition, this is the [model](https://drive.google.com/file/d/13rAilblasG3KZx8pXz1kxqkbL4Bmha59/view?usp=sharing) i want to convert, does this tool support this convertion ? or it support other action recognition model ?

**Comment by hxcai** [comment]
@wwdok We haven't tried it. You can use our tool to try.

**Comment by wwdok** [comment]
I have just tried it out, but it reports error:
```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~/Repo/mmaction2/tools$ python onnx2tensorrt.py
In node -1 (importIf): UNSUPPORTED_NODE: Assertion failed: cond.is_weights() && cond.weights().count() == 1 && "If condition must be a initializer!"
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
Traceback (most recent call last):
  File "onnx2tensorrt.py", line 10, in <module>
    trt_model = onnx2trt(model)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/volksdep/converters/onnx2trt.py", line 119, in onnx2trt
    trt_model = TRTModel(engine)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/volksdep/converters/base.py", line 50, in __init__
    self.context = self.engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

**Comment by hxcai** [comment]
@wwdok Here is unsupported operation in onnx model, maybe you can try to use higher opset_version in torch2onnx to convert pytorch model to onnx, and then use onnx2trt to convert onnx to tensorrt engine.

**Comment by wwdok** [comment]
Yes, the unsupported operation in onnx model is `if`, i found a solution [here](https://www.codenong.com/jsf226e3a24cc4/), and solved it by using torch 1.5 to export the onnx [model](https://drive.google.com/file/d/1en7Ro5zfiVsGHLJdpUE6c1OkeINV_Wr2/view?usp=sharing), and now the tensorrt model also is successfully exported. In the meantime, i convert the onnx model by [trtexec](https://github.com/NVIDIA/TensorRT/blob/988180050775c93d3612e06c410b8cd187d7c760/samples/opensource/trtexec/README.md), i found the .engine file size exported by  volksdep(101.6MB ) and trtexec(122.6MB) are different, so I am curious what are the differences inside, could you please tell me ?

**Comment by hxcai** [comment]
@wwdok Please make sure that the two engine files are generated in the same environment and with same params like platform, os, cuda version, tensorrt version, fp mode, work_spacesize and etc.. Also, trtexec is implement with c++ api and ours is implemented with python api, this may make different.

**Comment by wwdok** [comment]
Yes, they are converted on the same environment, for fp mode i didn't set, i just use default( for volksdep is fp32 ). Thansk for your reply, i think i need more time to get familiar with tensorrt ~
