### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator DeformConvFunction

### ISSUE THREAD

**Issue by hoang880805** [Media-Smart/volksdep#12]
Hi, 
I'm trying to convert pytorch model (tinaface) to onnx format but it was fail.

Error log is as below:

> root@1ce0ebf9a4bc:/workspace/vedadet# python tools/torch2onnx.py configs/trainval/tinaface/tinaface.py ../tinaface_r50_fpn_widerface.pth test.onnx --dummy_input_shape 3,640,640
Convert to Onnx with constant input shape 3,640,640 and opset version 9
Traceback (most recent call last):
  File "tools/torch2onnx.py", line 65, in <module>
    main()
  File "tools/torch2onnx.py", line 60, in main
    verbose=args.verbose)
  File "/opt/conda/lib/python3.6/site-packages/volksdep/converters/torch2onnx.py", line 62, in torch2onnx
    dynamic_axes=dynamic_axes)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 172, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 545, in _export
    val_add_node_names, val_use_external_data_format, model_file_location)
RuntimeError: ONNX export failed: Couldn't export Python operator DeformConvFunction
Defined at:
/workspace/vedadet/vedadet/ops/dcn/deform_conv.py(302): forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(561): _slow_forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(575): __call__
/workspace/vedadet/vedadet/models/backbones/resnet.py(274): _inner_forward
/workspace/vedadet/vedadet/models/backbones/resnet.py(297): forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(561): _slow_forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(575): __call__
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py(100): forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(561): _slow_forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(575): __call__
/workspace/vedadet/vedadet/models/backbones/resnet.py(630): forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(561): _slow_forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(575): __call__
/workspace/vedadet/vedadet/models/detectors/single_stage_detector.py(35): forward_impl
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(561): _slow_forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(575): __call__
/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py(394): wrapper
/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py(408): forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(577): __call__
/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py(320): _get_trace_graph
/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py(319): _trace_and_get_graph_from_model
/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py(366): _model_to_graph
/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py(530): _export
/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py(92): export
/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py(172): export
/opt/conda/lib/python3.6/site-packages/volksdep/converters/torch2onnx.py(62): torch2onnx
tools/torch2onnx.py(60): main
tools/torch2onnx.py(65): <module>

> 

This op isn't be support by volksdep, right?
Please help me confirm it.

**Comment by hxcai** [comment]
@hoang880805 Yes, deform conv op is not supported right now.

**Comment by hoang880805** [comment]
@hxcai  I got it so do you know any plan for support it?

**Comment by hoang880805** [comment]
@hxcai  i found some information at https://github.com/pytorch/pytorch/issues/15864.
