### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_execytion_context'

### ISSUE THREAD

**Issue by hotpeppeper** [Media-Smart/volksdep#15]
when i run the sample code:
```
dummy_input = torch.ones(1, 3, 224, 224).cuda()
model = torchvision.models.resnet18().cuda().eval()
## build trt model with fp32 mode
trt_model = torch2trt(model, dummy_input)
```
raise the error

env:
  cuda: 10.2
  tensorrt: 8
  pytorch: 1..0

**Comment by hxcai** [comment]
@hotpeppeper We haven't test with TensorRT 8, you can use TensorRT 7 if possible

**Comment by hxcai** [comment]
@hotpeppeper Hi, I have test the code with the following environment, and I can run the code successfully.
CUDA 10.2
TensorRT 8.0.1.6
PyTorch 1.6.0
