### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by choozhenbo** [Media-Smart/volksdep#18]
I did follow the steps to install tensorRT 8.4.1 and pytorch. After execute the command pip install "git+https://github.com/Media-Smart/volksdep.git", it shows the error below:
Collecting git+https://github.com/Media-Smart/volksdep.git
  Cloning https://github.com/Media-Smart/volksdep.git to /tmp/pip-req-build-fucad071
  Running command git clone --filter=blob:none -q https://github.com/Media-Smart/volksdep.git /tmp/pip-req-build-fucad071
  Resolved https://github.com/Media-Smart/volksdep.git to commit 9720829054b4cbb39ff02fe503663baf4d50812f
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/tham/anaconda3/envs/volksdep/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fucad071/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fucad071/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vl0o25m0
       cwd: /tmp/pip-req-build-fucad071/
  Complete output (34 lines):
  ERROR: Could not find a version that satisfies the requirement tensorrt>=7.1.0.* (from versions: 0.0.1.dev5, 0.0.1)
  ERROR: No matching distribution found for tensorrt>=7.1.0.*
  /home/tham/.local/lib/python3.6/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    SetuptoolsDeprecationWarning,
  Traceback (most recent call last):
    File "/home/tham/.local/lib/python3.6/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/home/tham/anaconda3/envs/volksdep/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/home/tham/anaconda3/envs/volksdep/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpgvf7182z', '--quiet', 'tensorrt>=7.1.0.*']' returned non-zero exit status 1.
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-fucad071/setup.py", line 70, in <module>
      zip_safe=False,
    File "/home/tham/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/home/tham/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/home/tham/.local/lib/python3.6/site-packages/setuptools/dist.py", line 809, in fetch_build_eggs
      replace_conflicting=True,
    File "/home/tham/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 773, in resolve
      replace_conflicting=replace_conflicting
    File "/home/tham/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1056, in best_match
      return self.obtain(req, installer)
    File "/home/tham/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1068, in obtain
      return installer(requirement)
    File "/home/tham/.local/lib/python3.6/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/home/tham/.local/lib/python3.6/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/home/tham/anaconda3/envs/volksdep/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpgvf7182z', '--quiet', 'tensorrt>=7.1.0.*']' returned non-zero exit status 1.
  ----------------------------------------
WARNING: Discarding git+https://github.com/Media-Smart/volksdep.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
May I know how to solve this issue?
These are the command howI install TensorRT:
sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/11.2.0/local_installers/cuda-repo-ubuntu1804-11-2-local_11.2.0-460.27.04-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1804-11-2-local_11.2.0-460.27.04-1_amd64.deb
sudo apt-key add /var/cuda-repo-ubuntu1804-11-2-local/7fa2af80.pub
sudo apt-get update
sudo apt-get -y install cuda
sudo apt-get install tensorrt-libs
sudo apt-get install tensorrt-dev
dpkg -l | grep TensorRT
ii  libnvinfer-bin                                              8.4.1-1+cuda11.6                                  amd64        TensorRT binaries
ii  libnvinfer-dev                                              8.4.1-1+cuda11.6                                  amd64        TensorRT development libraries and headers
ii  libnvinfer-plugin-dev                                       8.4.1-1+cuda11.6                                  amd64        TensorRT plugin libraries
ii  libnvinfer-plugin8                                          8.4.1-1+cuda11.6                                  amd64        TensorRT plugin libraries
ii  libnvinfer-samples                                          8.4.1-1+cuda11.6                                  all          TensorRT samples
ii  libnvinfer8                                                 8.4.1-1+cuda11.6                                  amd64        TensorRT runtime libraries
ii  libnvonnxparsers-dev                                        8.4.1-1+cuda11.6                                  amd64        TensorRT ONNX libraries
ii  libnvonnxparsers8                                           8.4.1-1+cuda11.6                                  amd64        TensorRT ONNX libraries
ii  libnvparsers-dev                                            8.4.1-1+cuda11.6                                  amd64        TensorRT parsers libraries
ii  libnvparsers8                                               8.4.1-1+cuda11.6                                  amd64        TensorRT parsers libraries
ii  python3-libnvinfer                                          8.4.1-1+cuda11.6                                  amd64        Python 3 bindings for TensorRT
ii  tensorrt                                                    8.4.1.5-1+cuda11.6                                amd64        Meta package for TensorRT
ii  tensorrt-dev                                                8.4.1.5-1+cuda11.6                                amd64        Meta package for TensorRT development libraries
ii  tensorrt-libs                                               8.4.1.5-1+cuda11.6                                amd64        Meta package for TensorRT runtime libraries

**Comment by hxcai** [comment]
@choozhenbo The GPU you used is from AMD? We only test on NVIDIA GPU

**Comment by choozhenbo** [comment]
@hxcai I am using NVIDIA GPU, and I solved it

**Comment by choozhenbo** [comment]
Dear Hong Xiang,

I am using NVIDIA GPU.
