### ISSUE TITLE
is ReformatFreeIO supported?

### ISSUE THREAD

**Issue by whatlas** [Media-Smart/volksdep#2]
there's a feature in TensorRT called [ReformatFreeIO](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#reformat-free-network-tensors), is this supported?
and if supported, how to set dynamic range for tensors using this project?

**Comment by hxcai** [comment]
@whatlas Hi, this feature is not supported yet.

**Comment by whatlas** [comment]
> @whatlas Hi, this feature is not supported yet.

thks , i got another issue when using this project.
