### ISSUE TITLE
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.

### ISSUE THREAD

**Issue by ghost** [Media-Smart/volksdep#6]
when I convert yolo4-tiny, this warning occurred,could you tell me how can I solve this problem? Thank you
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.

**Comment by hxcai** [comment]
you can use torch2onnx with specified opset version  to convert pytorch model to onnx, and then convert the onnx model to tensorrt engine
