### ISSUE TITLE
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1045, condition: profileMinDims.d[i] <= dimensions.d[i]

### ISSUE THREAD

**Issue by ischihmo** [Media-Smart/volksdep#8]
我的环境：
python 3.6.9
pytorch 1.6.0
cuda 10.2
tensorrt 7.1.3.0

按照readme文档操作，我将pytorch模型直接转成trt模型，过程中也没有报错。
随后加载trt模型进行预测，图像加载到网络后，报错如下：
```
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1045, condition: profileMinDims.d[i] <= dimensions.d[i]
```
此时打印trt网络的输出并与pytorch网络的输出相比较，网络的输出也是不一致的。
我不知道应该怎么解决这个问题，希望您能帮我解答。

**Comment by hxcai** [comment]
@VIRGoMerz 请查看一下输入数据的维度是否改变，目前trt模型仅支持batch维度是动态的，c，h，w维度需要保持一致

**Comment by ischihmo** [comment]
@hxcai 感谢指导，确实是输入图片的尺寸问题。
